services:
  my-nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - shared
    restart: unless-stopped

  my-acme-companion:
    image: nginxproxy/acme-companion
    depends_on:
      - my-nginx-proxy
    environment:
      - DEFAULT_EMAIL=spinatp@gmail.com  # email gets errors
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - shared
    restart: unless-stopped

volumes:
  certs:
  vhostd:
  html:

networks:
  shared:
    external: true
    name: my_tailt_shared_net
