services:
  my-nginx-proxy:
    image: jwilder/nginx-proxy:alpine # keep this setting for automatically refreshing docker
    container_name: my-nginx-proxy # keep this setting for automatically refreshing docker
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d # setup location here
      - html:/usr/share/nginx/html
    networks:
      - shared
    restart: unless-stopped

  my-acme-companion:
    image: nginxproxy/acme-companion # keep this setting for automatically refreshing docker
    container_name: my-acme-companion # keep this setting for automatically refreshing docker
    volumes_from:
      - my-nginx-proxy
    environment:
      - NODE_ENV=production
      - DEFAULT_EMAIL=spinatp@gmail.com # email gets errors
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    networks:
      - shared
    restart: unless-stopped

volumes:
  certs:
  html:
  acme:
  vhost:

networks:
  shared:
    external: true
    name: my_tailt_shared_net
