name: "Build and deploy nginx to server"

on:
  push:
    branches:
      - feature/final

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.ONLINE_HOST }} # ip of server
          username: ${{ secrets.ONLINE_USERNAME }} # Username to login to server
          key: ${{ secrets.ONLINE_SSH_PRIVATE_KEY }} # Private key to login to server

          script: |
            set -e

            docker container stop my-acme-companion || true
            docker container stop my-nginx-proxy || true

            docker container remove my-acme-companion || true
            docker container remove my-nginx-proxy || true

            docker image remove nginxproxy/acme-companion || true
            docker image remove jwilder/nginx-proxy:alpine || true

            cd ${{ secrets.ONLINE_PATH_PROJECT }} 

            if [ -d my-nginx ]; then
              cd my-nginx
              git fetch 
              git pull
            else
              git clone -b feature/final https://github.com/astropop/my-nginx.git
              cd my-nginx
            fi

            docker compose build
            docker compose up -d
